-- baseball.PitchData definition

CREATE TABLE `PitchData` (
  `pitch_type` text,
  `game_date` datetime DEFAULT NULL,
  `release_speed` double DEFAULT NULL,
  `release_pos_x` double DEFAULT NULL,
  `release_pos_z` double DEFAULT NULL,
  `player_name` text,
  `batter` bigint DEFAULT NULL,
  `pitcher` bigint DEFAULT NULL,
  `events` text,
  `description` text,
  `spin_dir` bigint DEFAULT NULL,
  `spin_rate_deprecated` bigint DEFAULT NULL,
  `break_angle_deprecated` bigint DEFAULT NULL,
  `break_length_deprecated` bigint DEFAULT NULL,
  `zone` bigint DEFAULT NULL,
  `des` text,
  `game_type` text,
  `stand` text,
  `p_throws` text,
  `home_team` text,
  `away_team` text,
  `type` text,
  `hit_location` bigint DEFAULT NULL,
  `bb_type` text,
  `balls` bigint DEFAULT NULL,
  `strikes` bigint DEFAULT NULL,
  `game_year` bigint DEFAULT NULL,
  `pfx_x` double DEFAULT NULL,
  `pfx_z` double DEFAULT NULL,
  `plate_x` double DEFAULT NULL,
  `plate_z` double DEFAULT NULL,
  `on_3b` bigint DEFAULT NULL,
  `on_2b` bigint DEFAULT NULL,
  `on_1b` bigint DEFAULT NULL,
  `outs_when_up` bigint DEFAULT NULL,
  `inning` bigint DEFAULT NULL,
  `inning_topbot` text,
  `hc_x` double DEFAULT NULL,
  `hc_y` double DEFAULT NULL,
  `tfs_deprecated` bigint DEFAULT NULL,
  `tfs_zulu_deprecated` bigint DEFAULT NULL,
  `umpire` bigint DEFAULT NULL,
  `sv_id` text,
  `vx0` double DEFAULT NULL,
  `vy0` double DEFAULT NULL,
  `vz0` double DEFAULT NULL,
  `ax` double DEFAULT NULL,
  `ay` double DEFAULT NULL,
  `az` double DEFAULT NULL,
  `sz_top` double DEFAULT NULL,
  `sz_bot` double DEFAULT NULL,
  `hit_distance_sc` bigint DEFAULT NULL,
  `launch_speed` double DEFAULT NULL,
  `launch_angle` bigint DEFAULT NULL,
  `effective_speed` double DEFAULT NULL,
  `release_spin_rate` bigint DEFAULT NULL,
  `release_extension` double DEFAULT NULL,
  `game_pk` bigint DEFAULT NULL,
  `fielder_2` bigint DEFAULT NULL,
  `fielder_3` bigint DEFAULT NULL,
  `fielder_4` bigint DEFAULT NULL,
  `fielder_5` bigint DEFAULT NULL,
  `fielder_6` bigint DEFAULT NULL,
  `fielder_7` bigint DEFAULT NULL,
  `fielder_8` bigint DEFAULT NULL,
  `fielder_9` bigint DEFAULT NULL,
  `release_pos_y` double DEFAULT NULL,
  `estimated_ba_using_speedangle` double DEFAULT NULL,
  `estimated_woba_using_speedangle` double DEFAULT NULL,
  `woba_value` double DEFAULT NULL,
  `woba_denom` bigint DEFAULT NULL,
  `babip_value` bigint DEFAULT NULL,
  `iso_value` bigint DEFAULT NULL,
  `launch_speed_angle` bigint DEFAULT NULL,
  `at_bat_number` bigint DEFAULT NULL,
  `pitch_number` bigint DEFAULT NULL,
  `pitch_name` text,
  `home_score` bigint DEFAULT NULL,
  `away_score` bigint DEFAULT NULL,
  `bat_score` bigint DEFAULT NULL,
  `fld_score` bigint DEFAULT NULL,
  `post_away_score` bigint DEFAULT NULL,
  `post_home_score` bigint DEFAULT NULL,
  `post_bat_score` bigint DEFAULT NULL,
  `post_fld_score` bigint DEFAULT NULL,
  `if_fielding_alignment` text,
  `of_fielding_alignment` text,
  `spin_axis` bigint DEFAULT NULL,
  `delta_home_win_exp` double DEFAULT NULL,
  `delta_run_exp` double DEFAULT NULL,
  `bat_speed` bigint DEFAULT NULL,
  `swing_length` bigint DEFAULT NULL,
  `estimated_slg_using_speedangle` double DEFAULT NULL,
  `delta_pitcher_run_exp` double DEFAULT NULL,
  `hyper_speed` double DEFAULT NULL,
  `home_score_diff` bigint DEFAULT NULL,
  `bat_score_diff` bigint DEFAULT NULL,
  `home_win_exp` double DEFAULT NULL,
  `bat_win_exp` double DEFAULT NULL,
  `age_pit_legacy` bigint DEFAULT NULL,
  `age_bat_legacy` bigint DEFAULT NULL,
  `age_pit` bigint DEFAULT NULL,
  `age_bat` bigint DEFAULT NULL,
  `n_thruorder_pitcher` bigint DEFAULT NULL,
  `n_priorpa_thisgame_player_at_bat` bigint DEFAULT NULL,
  `pitcher_days_since_prev_game` bigint DEFAULT NULL,
  `batter_days_since_prev_game` bigint DEFAULT NULL,
  `pitcher_days_until_next_game` bigint DEFAULT NULL,
  `batter_days_until_next_game` bigint DEFAULT NULL,
  `api_break_z_with_gravity` double DEFAULT NULL,
  `api_break_x_arm` double DEFAULT NULL,
  `api_break_x_batter_in` double DEFAULT NULL,
  `arm_angle` bigint DEFAULT NULL,
  `insert_time` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;